### ISSUE TITLE
Relay works very limited

### ISSUE THREAD

**Issue by Perlover** [lnbits/nostrclient#14]
I have my own LNBits instance and I have specified a lot of relays (from admin account of course). Then I specified only my relay based on your extension in the Nostr client. But because I see that he does not broadcast / receive all the events. For example, inside Amethyst client for a profiles there don't load user profiles (avatars aren't shown) and sending posts doesn't work. Is this normal for this version (that is, it is still raw and not working)? Or should everything work?

**Comment by TheFockinFury** [comment]
Experiencing something similar. When I remove all my relays from my client such that my only relay is the LNBits client, I don’t see most of my followers’ notes and events, and my follower count goes way down. I wonder if the problem is between my keyboard and chair?

**Comment by callebtc** [comment]
It's likely that especially social clients will have weird issues with this extension. It's very hard to predict how clients will react when they get their EOSE events. Some seem to work fine while others don't.

**Comment by bitkarrot** [comment]
yep, same here, been on amethyst (android) all week and without some extra backup relays, I'd have few to none posts coming through.  Time to read the code base and NIPs, I guess
