### ISSUE TITLE
Public websocket connections not accepted

### ISSUE THREAD

**Issue by santyr** [lnbits/nostrclient#26]
Prior to 0.4.0 I was able to connect to the nostr client using ws://localhost:3002/api/v1/relay.  

Now the connection fails:

Feb 10 13:31:53 AzagSat poetry[3104821]: 2024-02-10 13:31:53.72 | INFO | New websocket connection at: '/api/v1/relay'         
Feb 10 13:31:53 AzagSat poetry[3104821]: 2024-02-10 13:31:53.72 | WARNING | Public websocket connections not accepted.
Feb 10 13:31:53 AzagSat poetry[3104821]: 2024-02-10 13:31:53.72 | INFO | ('127.0.0.1', 46792) - "WebSocket /upgrades/4c81c2510
49599ef0ee32393b45fe5e4870ab02772dadb34e489b1a247411eca/nostrclient/api/v1/relay" 403     
Feb 10 13:31:53 AzagSat poetry[3104821]: 2024-02-10 13:31:53.72 | INFO | connection failed (403 Forbidden)                    
Feb 10 13:31:53 AzagSat poetry[3104821]: 2024-02-10 13:31:53.73 | INFO | connection closed

Am I doing something wrong?   

Rolling back to version 0.3.7 "fixes" the issue.

**Comment by santyr** [comment]
Note:  the interface still shows /nostrclient/api/v1/relay instead of the new url /nostrclient/api/v1/{relay_endpoint}

![image](https://github.com/lnbits/nostrclient/assets/792024/90f5554a-8eb3-473f-9ccd-d176bf7e5506)

**Comment by motorina0** [comment]
To avoid spamming, now there is an option if the websocket will accept only `Private` connections from other extensions (like `nostrmarket`) or it will accept also `Public` connections from anyone.

Please check if the `Public` option is enabled.


![image](https://github.com/lnbits/nostrclient/assets/2951406/c87d0e0d-146b-48fe-ac73-04b5545e981c)


![image](https://github.com/lnbits/nostrclient/assets/2951406/75fb68ad-0c9d-4e38-a627-3290c28b1986)
